#Default warp location
default: default
#Defined warps
warps:
  default:
    world: world
    x1: -128
    z1: -128
    x2: 128
    z2: 128
#What to avoid the user landing on
avoid:
  water: true
  lava: true
  trees: true
#Height to drop player into place with (No fall damage is incured if it is, set to a value less than 4)
drop-height: 8
#Shouldn't need to but checks the full distance from drop point to ground (adds aditional check, can lower performance. Helps avoid player landing in trees)
check-drop: false
#Attempts to find a location to warp the player to
attempts: 10
#If a suitable location can't be found, warp them somewhere even if it may be on
#something that was being avoided.
always-teleport: true
#Is the plugin enabled (i.e. Can players use it)
enable: true
#Display extra information in the console for debugging
debug: false
#Default permissions settings
permissions:
  #Op has all permissions
  op: true
  #Use Bukkit permissions
  bukkit: true
  #Use Vault permissions
  vault: false
  #Default permissions for ALL players ireespective of other permissions/plugins (can be all set to false for default confiruration)
  default:
    admin: false
    user: true
    warps:
      default: true
    warpother: false