name: RandomWarp
main: me.flungo.bukkit.randomwarp.RandomWarp
version: 1.1.0
author: flungo
description: >
             Execute Commands usings Triggers
commands:
  rwarp:
    aliases: [randomwarp, randwarp]
    description: Random warp management
    usage: |          
        /<command> [name] - Warps to the specified random warp area or default if no name is provided.
permissions:
  rwarp.admin:
    description: Access to all commands.
  rwarp.user:
    description: Allows player to use the command.
  rwarp.warps.*:
    description: Allows user to access all warps.
  rwarp.warpother:
    description: Allows user to warp other players to a random location.